# 3 数字日期和时间

Contents:

* 3.1 数字的四舍五入
* 3.2 执行精确的浮点数运算
* 3.3 数字的格式化输出
* 3.4 二八十六进制整数
* 3.5 字节到大整数的打包与解包
* 3.6 复数的数学运算
* 3.7 无穷大与NaN
* 3.8 分数运算
* 3.9 大型数组运算
* 3.10 矩阵与线性代数运算
* 3.11 随机选择
* 3.12 基本的日期与时间转换
* 3.13 计算上一个周五的日期
* 3.14 计算当前月份的日期范围
* 3.15 字符串转换为日期
* 3.16 结合时区的日期操作

## 3.1 数字的四舍五入

ans: 对于简单的舍入运算，使用内置的 `round(value, ndigits)` 函数即可。

In [2]:
print(round(1.23, 1))
print(round(1.27, 1))
print(round(-1.27, 1))
print(round(1.25361,1))

# 当一个值刚好在两个边界的中间的时候， round 函数返回离它最近的偶数。
a = 1627731
print(round(a, -1))
print(round(a, -2))
print(round(a, -3))

1.2
1.3
-1.3
1.3
1627730
1627700
1628000


In [5]:
# 不要将舍入和格式化输出搞混淆了!
x = 1.23456
print(format(x, '0.2f'))
print(format(x, '0.3f'))
print('value is {:0.3f}'.format(x))

# 不要试着去舍入浮点值来”修正”表面上看起来正确的问题
a = 2.1
b = 4.2
c = a + b
print(c)
c = round(c, 2) 
print(c)

1.23
1.235
value is 1.235
6.300000000000001
6.3


## 3.2 执行精确的浮点数运算

problem: 你需要对浮点数执行精确的计算操作，并且不希望有任何小误差的出现。

ans: `decimal` 模块

In [7]:
# 浮点数的一个普遍问题是它们并不能精确的表示十进制数。
a = 4.2
b = 2.1
print(a + b)
print(a +b == 6.3)

6.300000000000001
False


In [9]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
print(a + b)
print( a + b == Decimal('6.3'))

6.3
True


In [12]:
# decimal 模块的一个主要特征是允许你控制计算的每一方面，包括数字位数和四舍五入运算。 
# 为了这样做，你先得创建一个本地上下文并更改它的设置
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

with localcontext() as ctx:
    ctx.prec = 20
    print(a / b)

0.7647058823529411764705882353
0.765
0.76470588235294117647


In [14]:
# 你也得注意下减法删除以及大数和小数的加分运算所带来的影响
nums = [1.23e+18, 1, -1.23e+18]
print(sum(nums))

# 解决方法：
import math
print(math.fsum(nums))

0.0
1.0


## 3.3 数字的格式化输出

problem: 你需要将数字格式化后输出，并控制数字的位数、对齐、千位分隔符和其他的细节。

ans: `format()`

In [22]:
# 格式化输出单个数字的时候，可以使用内置的 format() 函数
x = 1234.56789
# Two decimal places of accuracy
print(format(x, '.2f'))
# Right justified in 10 chars, one-digit accuracy
print(format(x, '>10.1f'))
# Left justified
print(format(x, '<10.1f'))
# Centered
print(format(x, '^10.1f'))
# Inclusion of thousands separator
print(format(x, ','))
print(format(x, '0,.1f'))

1234.57
    1234.6
1234.6    
  1234.6  
1,234.56789
1,234.6


In [23]:
# 如果你想使用指数记法，将f改成e或者E(取决于指数输出的大小写形式)
print(format(x, 'e'))
print(format(x, '0.2E'))

1.234568e+03
1.23E+03


In [24]:
# 同时指定宽度和精度的一般形式是 '[<>^]?width[,]?(.digits)?' 
# 其中 width 和 digits 为整数，？代表可选部分。 
# 同样的格式也被用在字符串的 format() 方法中。
print('The value is {:0,.2f}'.format(x))

The value is 1,234.57


## 3.4 二八十六进制整数

problem: 你需要转换或者输出使用二进制，八进制或十六进制表示的整数。

ans: `bin()`, `oct()`, `hex()`

In [27]:
x = 1234
print(bin(x))
print(oct(x))
print(hex(x))

# 如果你不想输出 0b , 0o 或者 0x 的前缀的话，可以使用 format() 函数
print(format(x, 'b'))
print(format(x, 'o'))
print(format(x, 'x'))

0b10011010010
0o2322
0x4d2
10011010010
2322
4d2


In [7]:
# 整数是有符号的，所以如果你在处理负数的话，输出结果会包含一个负号
x = -1234
print(format(x, 'b'))
print(format(x, 'x'))

# 如果你想产生一个无符号值，你需要增加一个指示最大位长度的值
print(format(2**32 + x, 'b'))
print(format(2**32 + x, 'x'))

-10011010010
-4d2
11111111111111111111101100101110
fffffb2e


In [9]:
# 为了以不同的进制转换整数字符串，简单的使用带有进制的 int() 函数即可
print(int('4d2', 16))
print(int('10011010010', 2))

1234
1234


使用八进制的程序员有一点需要注意下。 Python指定八进制数的语法跟其他语言稍有不同。比如，如果你像下面这样指定八进制，会出现语法错误:

In [12]:
import os
# os.chmod('script.py', 0755)  # ERROR!
os.chmod('script.py', 0o755)  # 0o

## 3.5 字节到大整数的打包与解包

problem: 你有一个字节字符串并想将它解压成一个整数。或者，你需要将一个大整数转换为一个字节字符串。

ans: `int.from_bytes()`, `int.to_bytes()`

In [16]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
print(len(data))
print(int.from_bytes(data, 'little'))
print(int.from_bytes(data, 'big'))

16
69120565665751139577663547927094891008
94522842520747284487117727783387188


In [21]:
# 为了将一个大整数转换为一个字节字符串，使用 int.to_bytes() 方法，并像下面这样指定字节数和字节顺序
x = 94522842520747284487117727783387188
print(x.to_bytes(16, 'big'))
print(x.to_bytes(16, 'little'))

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'


In [22]:
# 解压多个字节串并将结果合并为最终的结果
data
b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
import struct
hi, lo = struct.unpack('>QQ', data)
(hi << 64) + lo

94522842520747284487117727783387188

In [24]:
# 字节顺序规则(little或big)仅仅指定了构建整数时的字节的低位高位排列方式
x = 0x01020304
print(x.to_bytes(4, 'big'))
print(x.to_bytes(4, 'little'))

b'\x01\x02\x03\x04'
b'\x04\x03\x02\x01'


In [27]:
# 使用 int.bit_length() 方法来决定需要多少字节位来存储这个值
x = 523 ** 23
print(x)
print(x.bit_length())
nbytes, rem = divmod(x.bit_length(), 8)
if rem:
    nbytes += 1

print(x.to_bytes(nbytes, 'little'))

335381300113661875107536852714019056160355655333978849017944067
208
b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'


## 3.6 复数的数学运算

problem: 你写的最新的网络认证方案代码遇到了一个难题，并且你唯一的解决办法就是使用复数空间。 再或者是你仅仅需要使用复数来执行一些计算操作。

ans: 复数可以用使用函数 `complex(real, imag)` 或者是带有后缀j的浮点数来指定。

In [3]:
a = complex(2, 4)
b = 3 - 5j
print(a)
print(b)

# 对应的实部、虚部和共轭复数可以很容易的获取
print(a.real)
print(a.imag)
print(a.conjugate())  # 共轭复数

# 另外，所有常见的数学运算都可以工作：
print('a+b = ', a + b)
print('a*b = ', a * b)
print('a/b = ', a / b)
print('|a| = ', abs(a))

(2+4j)
(3-5j)
2.0
4.0
(2-4j)
a+b =  (5-1j)
a*b =  (26+2j)
a/b =  (-0.4117647058823529+0.6470588235294118j)
|a| =  4.47213595499958


In [4]:
# 如果要执行其他的复数函数比如正弦、余弦或平方根，使用 cmath 模块
import cmath
print(cmath.sin(a))
print(cmath.cos(a))
print(cmath.exp(a))

(24.83130584894638-11.356612711218174j)
(-11.36423470640106-24.814651485634187j)
(-4.829809383269385-5.5920560936409816j)


In [8]:
# Python中大部分与数学相关的模块都能处理复数。
# 比如如果你使用 numpy ，可以很容易的构造一个复数数组并在这个数组上执行各种操作:
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
print(a)
print(a + 2)
print(np.sin(a))

[2.+3.j 4.+5.j 6.-7.j 8.+9.j]
[ 4.+3.j  6.+5.j  8.-7.j 10.+9.j]
[   9.15449915  -4.16890696j  -56.16227422 -48.50245524j
 -153.20827755-526.47684926j 4008.42651446-589.49948373j]


Python的标准数学函数确实情况下并不能产生复数值，因此你的代码中不可能会出现复数返回值。
如果你想生成一个复数返回结果，你必须显示的使用 cmath 模块，或者在某个支持复数的库中声明复数类型的使用。

In [9]:
import cmath
print(cmath.sqrt(-1))

1j


## 3.7 无穷大与NaN

problem: 你想创建或测试正无穷、负无穷或NaN(非数字)的浮点数。

ans: Python并没有特殊的语法来表示这些特殊的浮点值，但是可以使用 `float()` 来创建它们。

In [13]:
a = float('inf')
b = float('-inf')
c = float('nan')
print(a, b, c)

# 为了测试这些值的存在，使用 math.isinf() 和 math.isnan() 函数。
import math
print(math.isinf(a))
print(math.isnan(c))

inf -inf nan
True
True


In [24]:
# 无穷大数在执行数学计算的时候会传播
a = float('inf')
print(a + 45)
print(a + 10)
print(10 / a)

# 但是有些操作时未定义的并会返回一个NaN结果
print(a / a)
b = float('-inf')
print(a + b)

# NaN值会在所有操作中传播，而不会产生异常
c = float('nan')
print(c + 23)
print(c / 2)
print(c * 2)
print(math.sqrt(c))

# NaN值的一个特别的地方时它们之间的比较操作总是返回False
d = float('nan')
print(c == d)
print(c is d)
# 由于这个原因，测试一个NaN值得唯一安全的方法就是使用 math.isnan()

inf
inf
0.0
nan
nan
nan
nan
nan
nan
False
False


## 3.8 分数运算

problem: 分数运算，不是小数运算

ans: `fractions`模块

In [39]:
# fractions 模块可以被用来执行包含分数的数学运算
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)

# Getting numerator/denominator
c = a * b
print(c.numerator, c.denominator)

# Converting to a float
print(float(c))

# Limiting the denominator of a value
print(c.limit_denominator(8))

# Converting a float to a fraction
x = 3.75
y = Fraction(*x.as_integer_ratio())
print(y)

27/16
35 64
0.546875
4/7
15/4


## 3.9 大型数组运算

problem: 你需要在大数据集(比如数组或网格)上面执行计算。

ans: 涉及到数组的重量级运算操作，可以使用 `NumPy` 库。

In [43]:
# Python lists
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x * 2)
# print(x + 10)   # ERROR!
print(x + y)

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]


In [46]:
# Numpy arrays
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax + 2)
print(ax + ay)
print(ax * ay)

[3 4 5 6]
[ 6  8 10 12]
[ 5 12 21 32]


In [47]:
# 计算多项式的值
def f(x):
    return 3*x**2 - 2*x + 7

f(ax)

array([ 8, 15, 28, 47])

In [48]:
# NumPy 还为数组操作提供了大量的通用函数，这些函数可以作为 math 模块中类似函数的替代。
print(np.sqrt(ax))
print(np.cos(ax))

[1.         1.41421356 1.73205081 2.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


使用这些通用函数要比循环数组并使用 math 模块中的函数执行计算要快的多。 因此，只要有可能的话尽量选择 NumPy 的数组方案。

底层实现中， NumPy 数组使用了C或者Fortran语言的机制分配内存。 也就是说，它们是一个非常大的连续的并由同类型数据组成的内存区域。 所以，你可以构造一个比普通Python列表大的多的数组。 比如，如果你想构造一个10,000*10,000的浮点数二维网格，很轻松：

In [51]:
grid = np.zeros(shape=(10000,10000), dtype=float)
print(grid)
grid += 10
print(grid)
print(np.sin(grid))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 ...
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]]
[[-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 ...
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]]


In [59]:
# numpy 多维数组
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
# Select row 1
print(a[1])
# Select column 1
print(a[:, 1])
# Select a subregion and change it
print(a[1:3, 1:3])

a[1:3, 1:3] += 10
print(a)

# Broadcast a row vector across an operation on all rows
b = a + [100, 101, 102, 103]
print(b)

# Conditional assignment on an array
print(np.where(a < 10, a, 10))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 2  6 10]
[[ 6  7]
 [10 11]]
[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]
[[101 103 105 107]
 [105 117 119 111]
 [109 121 123 115]]
[[ 1  2  3  4]
 [ 5 10 10  8]
 [ 9 10 10 10]]


## 3.10 矩阵与线性代数运算

problem: 你需要执行矩阵和线性代数运算，比如矩阵乘法、寻找行列式、求解线性方程组等等。

ans: `NumPy` 库矩阵对象 - `np.matrix`

In [4]:
import numpy as np
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
print(m)
# Return transpose
print(m.T)
# Return inverse
print(m.I)

# create a vector and multiply
v = np.matrix([[2], [3], [4]])
print(v)
print(m * v)

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]
[[2]
 [3]
 [4]]
[[ 8]
 [32]
 [ 2]]


In [ ]:
import numpy.linalg
